/**
 * Proof that the ts-rs drift guard trips (traps register #13).
 *
 * A gate that has never been seen to fail is indistinguishable from a gate that cannot
 * fail. This mutates `nysia-proto` twice, asserts `pnpm ts-drift` exits **1** each time —
 * drift specifically, not 2, which would mean the crate merely stopped compiling and the
 * proof passed for the wrong reason — then restores the files and asserts the guard is
 * clean again.
 *
 * Two probes, because the generated directory holds two kinds of file and one guard has to
 * cover both:
 *
 *  1. **A type.** Appends a new exported type and expects the guard to name it. The
 *     mutation is additive on purpose: adding a `SessionKind` variant would break the
 *     exhaustive `match` in its `Display` impl and turn a drift proof into a compile-error
 *     proof. The probe exports to a **subdirectory**, because ts-rs lets any type pick its
 *     own path with `#[ts(export_to = "...")]` and a guard that only listed the top level
 *     would stop comparing every nested binding without saying so.
 *
 *  2. **A value.** Changes a `FrameKind` discriminant and expects the guard to name
 *     `wireConstants.ts`. ts-rs exports types and not values, so the frame kind bytes, the
 *     protocol version and the credit-window defaults are generated by `nysia-proto`'s own
 *     `bindings` module instead. Without this probe the guard would protect the types and
 *     silently ignore the numbers — and a wrong kind byte misroutes binary data rather than
 *     failing to compile, so it is the half that fails quietly.
 *
 * Each probe is restored before the next runs, and the guard is re-checked clean in
 * between, so "probe 2 tripped" means probe 2 tripped and not that probe 1 was left behind.
 *
 * Failures are raised as exceptions rather than `process.exit`, because `exit` terminates
 * without unwinding and would leave the sources mutated on disk. Everything that can fail
 * runs inside a `try` whose `finally` writes the original bytes of both files back.
 *
 * What that does *not* cover, deliberately: a hard kill between a mutation and the restore
 * — Ctrl-C at the wrong moment, a `SIGKILL`, the machine losing power — still leaves the
 * file modified. No `finally` can defend against that, and installing signal handlers to
 * narrow the window would buy a smaller race rather than remove one. The backstop is CI's
 * clean-tree step, which fails the run if any gate leaves the working tree dirty; locally
 * the probe block is labelled so `git diff` says what happened and how to fix it. If you
 * are reading this because you found that block committed, delete it.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

import { findRepoRoot } from '../tools/lint-meta/src/repoRoot.ts';

const repoRoot = findRepoRoot();
const identity = join(repoRoot, 'crates', 'nysia-proto', 'src', 'identity.rs');
const frame = join(repoRoot, 'crates', 'nysia-proto', 'src', 'frame.rs');
const driftGuard = join(repoRoot, 'scripts', 'ts-drift.ts');

/**
 * The nested path the type probe must appear at, as the guard reports it.
 *
 * Not exported: importing this module would run the proof. The restore test spawns the
 * script as a child process and keeps its own copy of this string.
 */
const PROBE_BINDING = 'drift_probe/DriftProbe.ts';

/** The generated value module the second probe must move. */
const CONSTANTS_BINDING = 'wireConstants.ts';

/**
 * A test seam, read by `scripts/prove-ts-drift.restore.test.ts`.
 *
 * Set to `after-mutation` to make the proof fail on purpose immediately after it writes
 * the first probe. That is the path that used to leave a developer with a mutated working
 * tree, so it is the path that has to be exercised.
 */
const FAULT = process.env['NYSIA_PROVE_TS_DRIFT_FAULT'];

const PROBE = `
/// Temporary type appended by \`pnpm prove:ts-drift\`. If you are reading this in a commit,
/// the proof script died between mutating the file and restoring it — delete this block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export, export_to = "drift_probe/")]
pub struct DriftProbe {
    /// Present only so the exported type has a field.
    pub probe: u32,
}
`;

/**
 * The discriminant the value probe moves, and what it moves it to.
 *
 * A discriminant rather than an added variant: `FrameKind`'s `as_byte`, `as_str` and
 * `from_byte` are all exhaustive matches, so a new variant would stop the crate compiling
 * and the guard would exit 2. Changing a byte compiles cleanly and is exactly the drift
 * worth catching.
 */
const KIND_BYTE_BEFORE = 'Output = 1,';
const KIND_BYTE_AFTER = 'Output = 9,';

interface GuardRun {
  readonly status: number;
  readonly output: string;
}

function runGuard(): GuardRun {
  const result = spawnSync(process.execPath, [driftGuard], {
    cwd: repoRoot,
    encoding: 'utf8',
    shell: false,
  });
  const stdout = result.stdout ?? '';
  const stderr = result.stderr ?? '';
  process.stdout.write(stdout);
  process.stderr.write(stderr);
  return { status: result.status ?? -1, output: stdout + stderr };
}

/** A failed assertion. Thrown, never exited, so the `finally` restore still runs. */
class ProofFailure extends Error {}

function fail(message: string): never {
  throw new ProofFailure(message);
}

/** The guard must be passing, or a probe that trips proves nothing about the probe. */
function requireClean(when: string): void {
  const run = runGuard();
  if (run.status !== 0) {
    fail(`the guard was not clean ${when} (exit ${run.status})`);
  }
}

/**
 * Assert the guard tripped on drift and named `binding`.
 *
 * Naming it matters as much as tripping: a guard that reports drift without mentioning the
 * file the probe moved is comparing something else, and would keep reporting success for
 * the file nobody is watching.
 */
function requireTrips(binding: string, vacuity: string): void {
  const after = runGuard();
  if (after.status === 0) {
    fail(`nysia-proto changed and the guard still passed (expected ${binding} to move)`);
  }
  if (after.status !== 1) {
    fail(
      `expected exit 1 (drift); got ${after.status}. Exit 2 means the generator failed, ` +
        'which would make this proof pass for the wrong reason.',
    );
  }
  if (!after.output.includes(binding)) {
    fail(`the guard tripped but never named ${binding}. ${vacuity}`);
  }
}

/** Replace exactly one occurrence, or say so rather than silently doing nothing. */
function replaceOnce(source: Buffer, before: string, after: string, file: string): Buffer {
  const text = source.toString('utf8');
  const occurrences = text.split(before).length - 1;
  if (occurrences !== 1) {
    fail(
      `expected exactly one \`${before}\` in ${file}, found ${occurrences}. The probe has ` +
        'stopped mutating anything, so this proof would pass without exercising the guard.',
    );
  }
  return Buffer.from(text.replace(before, after), 'utf8');
}

// Bytes, not strings: reading and writing through utf8 would rewrite line endings on a
// CRLF checkout, and this script must put back exactly what it found.
const identityOriginal = readFileSync(identity);
const frameOriginal = readFileSync(frame);

let failure: string | undefined;

try {
  if (FAULT !== 'after-mutation') {
    requireClean('before the mutation');
  }

  // Probe 1 — a new exported type, in a subdirectory.
  writeFileSync(identity, Buffer.concat([identityOriginal, Buffer.from(PROBE, 'utf8')]));
  // The marker is what the restore test keys on: it proves the file really was mutated
  // before the failure path was taken, so a passing restore is not just a no-op.
  process.stderr.write(`prove:ts-drift: mutated ${identity}\n`);

  if (FAULT === 'after-mutation') {
    fail('injected fault (NYSIA_PROVE_TS_DRIFT_FAULT=after-mutation)');
  }

  requireTrips(
    PROBE_BINDING,
    'It is comparing the top level only, so every nested binding is silently outside the ' +
      'diff.',
  );

  writeFileSync(identity, identityOriginal);
  requireClean('after restoring identity.rs');

  // Probe 2 — a changed numeric value, which ts-rs does not export at all.
  writeFileSync(frame, replaceOnce(frameOriginal, KIND_BYTE_BEFORE, KIND_BYTE_AFTER, frame));
  process.stderr.write(`prove:ts-drift: mutated ${frame}\n`);

  requireTrips(
    CONSTANTS_BINDING,
    'The guard is watching the ts-rs type files and ignoring the generated values, so a ' +
      'frame kind byte could change in Rust without CI noticing — and a wrong kind byte ' +
      'misroutes binary data rather than failing to compile.',
  );
} catch (error) {
  if (!(error instanceof ProofFailure)) throw error;
  failure = error.message;
} finally {
  writeFileSync(identity, identityOriginal);
  writeFileSync(frame, frameOriginal);
}

if (failure !== undefined) {
  process.stderr.write(`prove:ts-drift FAILED — ${failure}\n`);
  process.exit(1);
}

const restored = runGuard();
if (restored.status !== 0) {
  process.stderr.write(
    `prove:ts-drift FAILED — the guard did not go clean again after restoring ` +
      `identity.rs and frame.rs (exit ${restored.status})\n`,
  );
  process.exit(1);
}

process.stdout.write(
  `prove:ts-drift OK — the guard trips on a new type (${PROBE_BINDING}, nested) and on a ` +
    `changed wire constant (${CONSTANTS_BINDING}), and clears when both are fixed\n`,
);
